language: c
matrix:
  include:
    - os: linux
      compiler: gcc
      env: TARGET=
    - os: linux
      compiler: clang
      env: TARGET=
    - os: linux
      compiler: gcc
      env: TARGET=debug
    - os: linux
      compiler: clang
      env: TARGET=debug
    - os: osx
      compiler: clang
      env: TARGET=
    - os: osx
      compiler: clang
      env: TARGET=debug
script: ./configure && make $TARGET
